name: Python CI and Log Commit

on:
  push:
    branches:
      - main  # Bisa sesuaikan dengan nama branch kamu
  pull_request:
    branches:
      - main  # Bisa sesuaikan dengan nama branch kamu

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan di Ubuntu (bisa juga pilih windows atau macos)

    steps:
    # Checkout kode dari GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Atur versi Python sesuai kebutuhan

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies jika ada

    # Jalankan script Python dan simpan outputnya ke file
    - name: Run Python script and save output
      run: |
        python autoftbot.py > output_log.txt  # Ganti dengan nama script kamu
        cat output_log.txt  # Untuk menampilkan hasilnya di log GitHub Actions

    # Commit hasil output_log.txt ke repositori
    - name: Commit and push output log
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output_log.txt
        git commit -m "Update output log"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token otomatis untuk push
