name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode dari GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python (pastikan versi Python sesuai)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies (kalau ada requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Jalankan script Python (misalnya dengan `python script.py`)
    - name: Run script
      run: |
        python autoftbot.py
